name: Pigeon
options:
  bundleIdPrefix: net.numa08
targets:
  Pigeon:
    type: application
    platform: iOS
    sources:
      - Pigeon
  PigeonTests:
    type: bundle.unit-test
    platform: iOS
    sources: PigeonTests
    dependencies:
      - target: Pigeon