name: Pigeon
options:
  bundleIdPrefix: net.numa08
targets:
  Pigeon:
    type: application
    platform: iOS
    sources:
      - Pigeon
    settings:
      base:
        IPHONEOS_DEPLOYMENT_TARGET: 11.2
  PigeonTests:
    type: bundle.unit-test
    platform: iOS
    sources: PigeonTests
    dependencies:
      - target: Pigeon