# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "cac8c0e5-8f7b-4831-828b-4f221ab6c131"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # increment_build_number

  # build your iOS app
  build_app(
    scheme: "Pigeon"
  )

  # upload to HockeyApp
  hockey(
    api_token: ENV['HOCKE_APP_TOKEN'],
    release_type: "2"
  )
end
